### ISSUE TITLE
Need a way to get the list of Official images from Docker.io

### ISSUE THREAD

**Issue by rhatdan** [containers/shortnames#1]
@thaJeztah Any ideas on how to get this list?

**Comment by thaJeztah** [comment]
Do you need to have a list once, or an API to get them? I think there's an API that's used by the Docker Hub UI, but not publicly documented. https://hub.docker.com/search?q=&type=image&image_filter=official

Do you have more details about your use-case?

**Comment by saschagrunert** [comment]
Beware that some of them may be deprecated, for example the openSUSE ones: https://hub.docker.com/_/opensuse

**Comment by rhatdan** [comment]
We would prefer to get the opensuse images from registry.suse.com then to get them from Docker.

@thaJeztah If you read the readme.md for this REPO, it describes what we are trying to do.  Basically we want to have a list of shortnames->longnames mapping in our container engines, for "official" images, and then to allow distributions to identify "official" images.  

In a perfect world I would have a script I could run that just before release we could get a list of all of the images for each registry that they consider "official" and add missing ones to the list of short names.

Currently going to the web site to get the list, requires human intervention, which is likely to fail.

**Comment by rhatdan** [comment]
@saschagrunert BTW, we are looking for input from the community on shortnames that should be added to the list.  Would love to have a list of suse images, added.  

Having the community monitoring the list, will help fix issues that arrive in the future.

**Comment by vrothberg** [comment]
@sysrich FYI

**Comment by sysrich** [comment]
The correct place for openSUSE images would be registry.opensuse.org not registry.suse.com (which would be the correct place for SLE images)

However, because openSUSE doesn't have a distribution named openSUSE, we don't have a container named opensuse either :)

The official openSUSE base containers are as follows

registry.opensuse.org/opensuse/tumbleweed - regular base container based on Tumbleweed
registry.opensuse.org/opensuse/busybox - trimmed down minimal container based on Tumbleweed
registry.opensuse.org/opensuse/leap - regular base container based on Leap

These are the 3 that I would say make the most sense to be included in this project.

There's also a whole bunch of official service containers in the registry.opensuse.org/opensuse namespace for stuff such as haproxy, redis, nginx, etc, but that's probably stretching things beyond the scope of this effort, right?

**Comment by rhatdan** [comment]
@sysrich We should have the conversation under the SUSE issue.

**Comment by vrothberg** [comment]
> There's also a whole bunch of official service containers in the registry.opensuse.org/opensuse namespace for stuff such as haproxy, redis, nginx, etc, but that's probably stretching things beyond the scope of this effort, right?

I think it's important to leave project names open to the respective projects. For instance, "busybox" should not resolve to "registry.opensuse.org/opensuse/busybox" unless that's what the "busybox" maintainers want. However, we can use "opensuse/busybox" for that if you want to.  Same for "redis", "nginx" and friends.

**Comment by rhatdan** [comment]
Sure and then the individual distros can modify the list and put there versions in.  If OpenSuse wants to add a link between busybox to their version, then they can do it.
The one exception to this rule would be the Docker official versions.  I think we should allow opensource projects to be allocated to docker.io, in the shortnames repo. If distros override, then that is their prerogative.

**Comment by rhatdan** [comment]
We decided to go with definitely distro  specific images, rather then general images.
