### ISSUE TITLE
Need official images from Debian

### ISSUE THREAD

**Issue by rhatdan** [containers/shortnames#2]

**Comment by vrothberg** [comment]
@siretart PTAL

**Comment by rhatdan** [comment]
@siretart is there an official location for debian images or do we just grab them from Docker.io?
Same question on Ubuntu images?

**Comment by siretart** [comment]
[sorry for the late answer]

To the best of my knowledge, these repositories are as official as it gets:

- https://hub.docker.com/_/debian
- https://hub.docker.com/_/ubuntu

Both are maintained by Debian (Ubuntu) Developers.

**Comment by rhatdan** [comment]
@siretart Mind opening a PR to add them.  That way I can blame you :^)

**Comment by siretart** [comment]
I notice in the current `shortnames.conf` file that distributions such as suse and rhel list quite a number of variants.
Debian has actually quite a number of tags: https://hub.docker.com/_/debian

Is it possible to specify a prefix or a pattern so that `podman pull debian/bullseye-slim` would fetch the right image? Or would you prefer to spell out the dozens of variants?

**Comment by vrothberg** [comment]
@siretart tags and digests are not allowed as short-name aliases.

I think Debian could be covered as `"debian" = "docker.io/library/debian"`. Tags and digests will be appended to the alias so if we do a `podman pull debian:foo` we'd be pulling `docker.io/library/debian:foo`.

**Comment by rhatdan** [comment]
RHEL and SUSE have different images rhel7, rhel6 rhel8 as opposed to tags in Centos
centos:6, centos:7, centos:8.  We believe that the user should specify tags if they don't want :latest, and that shortnames should not include the tag.

**Comment by rhatdan** [comment]
We now have a debian image.
