### ISSUE TITLE
Need offical images from SUSE

### ISSUE THREAD

**Issue by rhatdan** [containers/shortnames#3]

**Comment by sysrich** [comment]
In the same way that CentOS and RHEL are different, openSUSE and SUSE are different :)

The correct place for openSUSE images would be registry.opensuse.org not registry.suse.com (which would be the correct place for SLE / SUSE images)

On registry.opensuse.org, because openSUSE doesn't have a distribution named openSUSE, we don't have a container named opensuse either :)

The official openSUSE base containers are as follows

registry.opensuse.org/opensuse/tumbleweed - regular base container based on Tumbleweed
registry.opensuse.org/opensuse/busybox - trimmed down minimal container based on Tumbleweed
registry.opensuse.org/opensuse/leap - regular base container based on Leap

These are the 3 that I would say make the most sense to be included in this project.

There's also a whole bunch of official service containers in the registry.opensuse.org/opensuse namespace for stuff such as haproxy, redis, nginx, etc, but that's probably stretching things beyond the scope of this effort, right?

**Comment by rhatdan** [comment]
@sysrich I would like to get the list of suse images.

If a user does
podman pull suse
podman pull sle15

We need someone to open a PR with this repo giving us the list of image shortnames that SUSE/OpenSUSE would like to claim.

**Comment by rhatdan** [comment]
BTW I know there is a difference between OpenSUSE and SUSE.  Did not mean to make them seem the same.

**Comment by vrothberg** [comment]
Closing as SUSE images are now covered.
